# Uncomment the 'shield: nice_view' lines below if you are using nice!view displays.
# Additionally, you should enable the display feature in 'config/blecorne.conf'.
---
include:
  - board: blecorne
    shield: nice_view blecorne_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: blecorne
    shield: nice_view blecorne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: blecorne
    shield: blecorne_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_DISPLAY=n
